name: CI para C

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
    - name: Clonar o repositório
      uses: actions/checkout@v3

    - name: Instalar compilador GCC
      run: sudo apt update && sudo apt install build-essential -y

    - name: Compilar o programa
      run: gcc GitHub.C -o programa

    - name: executar o programa
      run: ./programa

    - name: Executar testes automáticos
      run: |
        gcc -teste teste.c
        ./teste
